development:
  client_id: dvdpost_client
  client_secret: 'dvdpost_client_secret'
  site: 'https://staging.sso.dvdpost.be'
  authorize_path: 'authorization/new'
  access_token_path: 'authorization/token'
test:
  client_id: dvdpost_client
  client_secret: 'dvdpost_client_secret'
  site: 'https://sso.dvdpost.dev'
  authorize_path: 'authorization/new'
  access_token_path: 'authorization/token'
staging:
  client_id: dvdpost_client
  client_secret: 'dvdpost_client_secret'
  site: 'https://staging.sso.dvdpost.be'
  authorize_path: 'authorization/new'
  access_token_path: 'authorization/token'
production:
  client_id: dvdpost_client
  client_secret: 'dvdpost_client_secret'
  site: 'https://sso.dvdpost.be'
  authorize_path: 'authorization/new'
  access_token_path: 'authorization/token'
