development:
  client_id: dvdpost_rails_development_client
  client_secret: 'dvdpost_rails_development_client_secret'
  site: 'https://staging.sso.dvdpost.be'
  authorize_path: 'authorization/new'
  access_token_path: 'authorization/token'
test:
  client_id: dvdpost_rails_development_client
  client_secret: 'dvdpost_rails_development_client_secret'
  site: 'https://dvdpost.dev'
  authorize_path: 'authorization/new'
  access_token_path: 'authorization/token'
staging:
  client_id: dvdpost_rails_staging_client
  client_secret: 'dvdpost_rails_staging_client_secret'
  site: 'https://staging.sso.dvdpost.be'
  authorize_path: 'authorization/new'
  access_token_path: 'authorization/token'
pre_production:
  client_id: dvdpost_rails_pre_prod_client
  client_secret: 'dvdpost_rails_pre_prod_client_secret'
  site: 'https://sso.dvdpost.be'
  authorize_path: 'authorization/new'
  access_token_path: 'authorization/token'
production:
  client_id: dvdpost_rails_client
  client_secret: dvdpost_rails_client_secret
  site: 'https://sso.dvdpost.be'
  authorize_path: 'authorization/new'
  access_token_path: 'authorization/token'
