development:
  port: 8444
  searchd_log_file: "log/searchd.log"
  query_log_file: "log/searchd_query.log"
  pid_file: "log/searchd.pid"
test:
  port: 8444
  pid_file: log/searchd.pid
  searchd_log_file: "log/searchd.log"
  query_log_file: "log/searchd_query.log"
  pid_file: "log/searchd.pid"
staging:
  port: 7444
  pid_file: log/searchd.pid
  searchd_log_file: "log/searchd.log"
  query_log_file: "log/searchd_query.log"
  pid_file: "log/searchd.pid"
pre_production:
  port: 6444
  pid_file: log/searchd.pid
  searchd_log_file: "log/searchd.log"
  query_log_file: "log/searchd_query.log"
  pid_file: "log/searchd.pid"
production:
  port: 5444
  pid_file: log/searchd.pid
  searchd_log_file: "log/searchd.log"
  query_log_file: "log/searchd_query.log"
  pid_file: "log/searchd.pid"